apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smashing-healthchecks-widget
  description: Smashing widget
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
  tags:
    - smashing-healthchecks-widget
    - ruby
  annotations:
    'github.com/project-slug': 'merou/smashing-healthchecks-widget'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: other
  lifecycle: unknown
  owner: merou
