apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smashing-healthchecks-widget
  annotations:
    github.com/project-slug: merou/smashing-healthchecks-widget
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: other
  lifecycle: unknown
  owner: merou
